### ISSUE TITLE
Light bleed while underground

### ISSUE THREAD

**Issue by Ayplow** [robobo1221/robobo1221Shaders#2]
I really hope I'm just missing some setting that will fix this, but this is a *massive* problem with using the pack. While underground, light and shadows from the surface seem to bleed into caves I am in.

PC:
Windows: 17746
Optifine: 1.12.2_HD_U_E2
Forge: 14.23.4.2756

![image](https://user-images.githubusercontent.com/25057690/44810584-0460db00-abca-11e8-9a10-ca8c94d8cf9f.png)

![image](https://user-images.githubusercontent.com/25057690/44810672-4c7ffd80-abca-11e8-88cd-1a8466b4506f.png)

**Comment by robobo1221** [comment]
Hey!

Unfortunately this can not be fixed. It's an Optifine issue wher caves
don't properly cast a shadow. The way to fix it is to render the mainland
before you go in caves. This way, the land above you casts a shadow and the
problem in caves is gone.

Hope this helps!

Op wo 29 aug. 2018 om 21:31 schreef MoreThanTom <notifications@github.com>:
