### ISSUE TITLE
Black screen on loading

### ISSUE THREAD

**Issue by Captainpewd** [robobo1221/robobo1221Shaders#3]
Using the latest version of Minecraft (1.13.2) and Optifine (1.13.2-OptiFine_HD_U_E5), loading up the shaderpack just leaves me with a black screen. Not sure what I'm doing wrong, as this is all that's inside the .zip file one step after opening, which I had to change myself after downloading from the repo. 
![image](https://user-images.githubusercontent.com/34585207/50404342-570f6580-076c-11e9-977a-33ac61ce9c5b.png)

**Comment by robobo1221** [comment]
Hey!

Make sure you have unzipped the zip. The folder structure should be as
following:

shaderpacks\robobo1221shaders\shaders\

Op ma 24 dec. 2018 om 18:09 schreef Captainpewd <notifications@github.com>:

**Comment by Captainpewd** [comment]
Yep, that's what it is. shaderpacks/robobo1221Shaders-7.9.01.zip, and right inside that zip is the shaders folder just like all the other packs I have installed which work fine.

**Comment by robobo1221** [comment]
You have to make a seperate folder inside your shaderpacks folder and put
the "shaders" folder that is inside the zip into that newely made folder.
Hopefully that should fix the problem

Op zo 30 dec. 2018 om 07:13 schreef Captainpewd <notifications@github.com>:
